name: OSX Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  testing:
    strategy:
      matrix:
        os: [macos-latest]
        setup: [unittests, functional]

    runs-on: ${{ matrix.os }}

    name: OS ${{ matrix.os }} - ${{ matrix.setup }} tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python requirements
        run: |
          pip install -r conans/requirements.txt
          pip install -r conans/requirements_server.txt
          pip install -r conans/requirements_dev.txt

      - name: Install Rosetta 2
        run: |
          /usr/sbin/softwareupdate --install-rosetta --agree-to-license

      - name: Install CMake versions
        working-directory: /tmp
        run: |
          wget -q --no-check-certificate https://cmake.org/files/v3.15/cmake-3.15.7-Darwin-x86_64.tar.gz
          tar -xzf cmake-3.15.7-Darwin-x86_64.tar.gz \
            --exclude=CMake.app/Contents/bin/cmake-gui \
            --exclude=CMake.app/Contents/doc/cmake \
            --exclude=CMake.app/Contents/share/cmake-3.15/Help \
            --exclude=CMake.app/Contents/share/vim
          mkdir -p ${HOME}/Applications/CMake/3.15.7
          cp -fR cmake-3.15.7-Darwin-x86_64/CMake.app/Contents/* ${HOME}/Applications/CMake/3.15.7
          rm -rf cmake-3.15.7-Darwin-x86_64
          rm cmake-3.15.7-Darwin-x86_64.tar.gz

      - name: Run Unit Tests
        run: |
          python -m pytest -x -v --color=auto test/${{ matrix.setup }}
