name: OSX Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  testing:
    strategy:
      matrix:
        os: [macos-latest]
        setup: [unittests, functional, performance, integration]

    runs-on: ${{ matrix.os }}

    name: OS ${{ matrix.os }} - ${{ matrix.setup }} tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python requirements
        run: |
          pip install -r conans/requirements.txt
          pip install -r conans/requirements_server.txt
          pip install -r conans/requirements_dev.txt

      - name: Run Unit Tests
        run: |
          python -m pytest -x -v --color=auto test/${{ matrix.setup }}
